version: '3'
services:
  decidim:
    restart: unless-stopped
    image: ghcr.io/codeandomexico/decidim-monterrey/production:1.3
    ports:
      - '8021:3000'
    env_file:
      - .env
    volumes:
      - /mnt/mtygobmx_decidim/data_storage:/decidim/storage
      - /mnt/mtygobmx_decidim/log_storage:/decidim/log
      - /tmp/decidim_tmp:/decidim/tmp
    entrypoint: /decidim/docker/entrypoints/decidim.sh
    command: "/decidim/bin/rails s -b 0.0.0.0"
  # ------------------------------
  # Delayed Job
  delayed_job:
    restart: unless-stopped
    image: ghcr.io/codeandomexico/decidim-monterrey/production:1.3
    command: "bundle exec rake jobs:work"
    env_file:
      - .env
    depends_on:
      - decidim
  # ------------------------------
  # Clockwork
  clockwork:
    restart: unless-stopped
    image: ghcr.io/codeandomexico/decidim-monterrey/production:1.3
    command: "bundle exec clockwork config/clockwork.rb"
    env_file:
      - .env
    depends_on:
      - decidim
volumes:
  tmp_cache: {}